### ISSUE TITLE
Documentation on devtoolsFormatter?

### ISSUE THREAD

**Issue by Daniel15** [andrewdavey/immutable-devtools#1]
Is there any documentation on `devtoolsFormatter` somewhere (or at least pointers to where it's used in the Chrome dev tools code)? Searching Google only returns a few examples of people using it, and no actual documentation.

**Comment by andrewdavey** [comment]
The best I could find is this: https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview

It's still in beta, so maybe it'll get proper docs later.

**Comment by Daniel15** [comment]
:+1: Thanks!
