### ISSUE TITLE
installDevTools(immutable) returns undefined.

### ISSUE THREAD

**Issue by kjr247** [andrewdavey/immutable-devtools#18]
Note that I also tried updating chrome. I will say that both import statements are valid as they both log out correct looking data for immutable and installDevTools from these two lines.

```
import immutable from 'immutable';
import installDevTools from 'immutable-devtools';

```

Yet when I log them out to install it, it's undefined such that: 
```
console.log('installDevTools', installDevTools(immutable));
const stuff = installDevTools(immutable);
console.log('thingers', stuff);
```
always logs undefined.

And the code below always just spits out unformatted immutablejs objects.
```
const thing = {
  'thing':"oop",
  'mop':"glop",
  'weeks': [
    {goop:"date"},
    {goop:"date"},
    {goop:"date"},
    {goop:"date"}
  ],
  'used': 'meep'
};

const schA = Map (thing);

console.log(schA);
```

**Comment by langpavel** [comment]
related to #15

**Comment by langpavel** [comment]
`installDevTools` should not return anything, it just instruct Chrome to use formatters.
