### ISSUE TITLE
Chrome >=48.0 required

### ISSUE THREAD

**Issue by JamieMason** [andrewdavey/immutable-devtools#27]
Thanks for this great tool @andrewdavey.

I notice that it can't be installed on versions of Chrome earlier than 48 and wondered, what work would be involved for older versions to be supported? Is it a case of introducing a few shims, or something much more involved?

**Comment by langpavel** [comment]
This tool is dependent on special Chrome (Chromium) feature which is not available before this version.

**Comment by JamieMason** [comment]
Thanks @langpavel, I thought that might be the case, but was hoping you could help me learn what feature(s) that was please?

**Comment by darwin** [comment]
custom formatters were introduced in early 2015, around Chrome 48:

https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/edit

**Comment by JamieMason** [comment]
Perfect, thanks @darwin – now all's clear 👍

**Comment by darwin** [comment]
If you really need to use CFs with Chrome older than v48, you could try to take DevTools from Chrome 48 and run it against Chrome 47 or older. It could work with a bit of luck or with small tweaks. Running current version of DevTools against Chrome 47 is not possible I guess, that would require a lot of compatibility work (after ~2 years of development).

See "Run Chrome with your own DevTools front-end" here:
https://docs.google.com/document/d/1WNF-KqRSzPLUUfZqQG5AFeU_Ll8TfWYcJasa_XGf7ro/view#heading=h.9t7np5fa400

https://github.com/binaryage/dirac/blob/master/docs/faq.md#why-should-i-use-recent-chrome-canary-with-dirac-devtools

**Comment by JamieMason** [comment]
That's cool, thanks @darwin – the effort would outweigh the return for that but I appreciate you offering up the idea. If it was a case of a few shims or patches or something, I'd have maybe put together a pull request to help out. Not a problem though, just curious.
