### ISSUE TITLE
Breaks with Immutable v4

### ISSUE THREAD

**Issue by elaye** [andrewdavey/immutable-devtools#30]
Hello,
Thanks for this addon, it's of great help!
I tried the new version of Immutable on my project and the formatters don't work anymore.
I only tried v4.0.0-rc.9 but I guess it's broken for the other rcs too, probably because of the [breaking changes](https://github.com/facebook/immutable-js/releases/tag/v4.0.0-rc.1) of v4.

**Comment by janeluck** [comment]
@elaye  it seams like this repository has not been maintain anymore. https://github.com/andrewdavey/immutable-devtools/pull/29 or [another devtool](https://github.com/mattzeunert/immutable-object-formatter-extension)

**Comment by mattzeunert** [comment]
Fixed now!
