### ISSUE TITLE
Not working with DevTools (server side)

### ISSUE THREAD

**Issue by Kronuz** [andrewdavey/immutable-devtools#31]
I'm using `node --inspect-brk` and `chrome://inspect` to debug the server side rendering (Using Webpack, React and Redux stack) but sure enough it says `window` object doesn't exist. maybe it should try installing those in `global` instead for it to work.

**Comment by Kronuz** [comment]
Yes, verified, it works if it uses `global` instead of `window` for that case.

**Comment by brainkim** [comment]
Any update on getting this merged in? :)

**Comment by mattzeunert** [comment]
This is merged now and published to NPM.
