### ISSUE TITLE
Idea: Add a bookmarklet?

### ISSUE THREAD

**Issue by Daniel15** [andrewdavey/immutable-devtools#4]
It would be handy to have this as a bookmarklet, so I could instantly inject it into a page that uses immutable-js without having to edit the site's code to pull this library in. Would that be possible? It looks like the formatter just needs to be added to the `window.devtoolsFormatters` array in the page's context. I guess the hard bit would be actually getting the reference to Immutable-js - It could probably assume there's either an `Immutable` global (eg. using immutable-js from CDN), or `require('immutable')` pulls it in (on some sites with CommonJS requires, eg. on Facebook).

**Comment by andrewdavey** [comment]
Yes it's possible. But as you said though, reliably getting a reference to Immutable is tricky.

**Comment by langpavel** [comment]
blocked by #20

**Comment by Daniel15** [comment]
@mattzeunert's extension (https://chrome.google.com/webstore/detail/immutablejs-object-format/hgldghadipiblonfkkicmgcbbijnpeog) works pretty well, closing this out.
