### ISSUE TITLE
Record types not shown correctly in all cases

### ISSUE THREAD

**Issue by jonaskello** [andrewdavey/immutable-devtools#5]
If I define an Immutable [Record](https://facebook.github.io/immutable-js/docs/#/Record), it seems the inspector cannot format it:

```js
	let MyRecord = Immutable.Record({foo: 4});
	let bar = new MyRecord({bar: 3});
```

![image](https://cloud.githubusercontent.com/assets/664076/11584584/533cc780-9a65-11e5-87c3-cee32179c9af.png)

 It would be nice if we could inspect Record types and directly see the properties on them.

**Comment by jonaskello** [comment]
Actually, it seems like it is already implemented but does not work all of the time. I have this code at a place in my larger code base:

```js
	let MyRecord = Immutable.Record({foo: 4});
	let bar = new MyRecord({foo: 3});
	debugger;
```

I print bar, then hit F8, then the next time I get to the debugger line, I print bar again. The third time around it works. Maybe has something to do with the remark "Object value at the left was snapshotted when logged, value below was evaluated just now." as seen in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/664076/11585413/3561a7c4-9a6c-11e5-9d94-ffffe65e294a.png)

**Comment by langpavel** [comment]
Hi @jonaskello 

Sorry for late response. Are you sure to install immutable-devtools before console was opened? There was some weird behavior of Chrome..
Can you please describe more in detail your problem (or solution if you got it), please?
Thanks a lot!

**Comment by langpavel** [comment]
Closing this one. Please reopen it if issue persist.

**Comment by jonaskello** [comment]
I've not seen this lately so probably it got fixed.

**Comment by langpavel** [comment]
@jonaskello Thanks for feedback
